### ISSUE TITLE
#Pragma Conference 17

### ISSUE THREAD

**Issue by darthpelo** [amobconf/awesome-mobile-conferences#5]
Is it possible to add a conference that it's over? #Pragma Conference 2017.

**Comment by matteocrippa** [comment]
Ciao @darthpelo `Pragma Conference 2017` was already listed ( https://github.com/amobconf/awesome-mobile-conferences/blob/master/contents.json ) but the readme generator was skipping that.

Btw I managed to tweak the generator creating a new section `Past` where all the finished conference are listed automatically.

Thank you for your suggestion!
